pre-release-replacements = [
  {file="../README.md", search="ritter = .*", replace="ritter = \"{{version}}\""},
  {file="../README.md", search="ritter-tool = .*", replace="ritter-tool = \"{{version}}\""},
]

consolidate-commits = true
shared-version = true
