[package]
name = "ritter-macro"
description = "Procedural macros for ritter"
readme = "../README.md"
repository = "https://github.com/jaboatman/ritter"
version.workspace = true
authors.workspace = true
edition = "2024"
license = "MIT"
keywords = ["parsing", "codegen"]
categories = ["development-tools"]

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
syn = { version = "2", features = [ "full", "extra-traits" ] }
quote = "1"
proc-macro2 = "1"
ritter-common = { path = "../common" }
ritter-types = { path = "../types" }

[dev-dependencies]
insta = "1"
tempfile = "3"
